text=input("enter a text:")
kalameh=text.split()
print("Total characters:",len(text))
print("Total kalameh:",len(kalameh))
print("total letters:",sum(i.isalpha()for i in text))
print("Total digits:",sum(i.isdigit()for i in text))
print("Total space:",text.count(""))
print("Total uppercase:",sum(i.isupper()for i in text))
print("Total lowercase:",sum(i.islower()for i in text))
print("longest word:",max(kalameh,key=len))
print("shortest word:",min(kalameh,key=len))
print(" most repeated characters:",max(set(text),key=text.count)if text else"")
print("most repeated word:",max(set(kalameh),key=kalameh.count)if kalameh else"")